import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Link, Route, Routes, useLocation, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { ArrowRight, CalendarDays, Check, ChevronDown, ChevronLeft, Clock3, Compass, Heart, MapPin, Menu, Search, ShieldCheck, Sparkles, Ticket, UserRound, X, Film, Music2, Trophy, Drama, Laugh, Popcorn, Tag } from 'lucide-react';
import { categories, events } from './data/events';
import './styles/app.css';

const navItems = ['Movies', 'Concerts', 'Sports', 'Theatre', 'Comedy'];

function App() {
  const [location, setLocation] = useState('Hyderabad');
  const [menuOpen, setMenuOpen] = useState(false);
  const [searchOpen, setSearchOpen] = useState(false);
  const [user, setUser] = useState(null);
  return <div className="app-shell">
    <Header location={location} setLocation={setLocation} menuOpen={menuOpen} setMenuOpen={setMenuOpen} searchOpen={searchOpen} setSearchOpen={setSearchOpen} user={user} />
    <Routes>
      <Route path="/" element={<Home location={location} />} />
      <Route path="/events" element={<EventsPage location={location} />} />
      <Route path="/movies" element={<EventsPage location={location} />} />
      <Route path="/concerts" element={<EventsPage location={location} />} />
      <Route path="/sports" element={<EventsPage location={location} />} />
      <Route path="/theatre" element={<EventsPage location={location} />} />
      <Route path="/comedy" element={<EventsPage location={location} />} />
      <Route path="/events/:id" element={<EventDetails />} />
      <Route path="/booking/:id" element={<BookingPage />} />
      <Route path="/login" element={<LoginPage setUser={setUser} />} />
      <Route path="/register" element={<RegisterPage />} />
      <Route path="/my-bookings" element={<BookingsPage />} />
      <Route path="/organizer" element={<RoleDashboard role="Organizer" />} />
      <Route path="/organizer/*" element={<RoleDashboard role="Organizer" />} />
      <Route path="/verifier" element={<RoleDashboard role="Verifier" />} />
      <Route path="/verifier/*" element={<RoleDashboard role="Verifier" />} />
      <Route path="*" element={<Home location={location} />} />
    </Routes>
  </div>;
}

function Header({ location, setLocation, menuOpen, setMenuOpen, searchOpen, setSearchOpen, user }) {
  const navigate = useNavigate();
  return <header className="site-header">
    <div className="header-inner">
      <Link className="brand" to="/"><span className="brand-mark"><Ticket size={18} strokeWidth={2.7} /></span><span>UNIVERSAL<span className="brand-red">TICKETS</span></span></Link>
      <button className="desktop-search" onClick={() => setSearchOpen(true)}><Search size={18} /><span>Search for Movies, Events, Plays, Sports and Activities</span></button>
      <div className="header-actions">
        <button className="location-button" onClick={() => setLocation(location === 'Hyderabad' ? 'Bengaluru' : 'Hyderabad')}>{location} <ChevronDown size={13} /></button>
        <button className="mobile-search" aria-label="Search" onClick={() => setSearchOpen(true)}><Search size={18} /></button>
        {user ? <button className="profile-button" onClick={() => navigate('/my-bookings')}><UserRound size={16} /> Rahul</button> : <Link className="login-link" to="/login">Sign in</Link>}
        <button className="mobile-menu" onClick={() => setMenuOpen(!menuOpen)} aria-label="Menu">{menuOpen ? <X size={21} /> : <Menu size={21} />}</button>
      </div>
    </div>
    <div className={menuOpen ? 'nav-bar open' : 'nav-bar'}><div className="nav-inner"><nav className="main-nav">{navItems.map(item => <Link key={item} to={`/events?category=${item.toLowerCase()}`} onClick={() => setMenuOpen(false)}>{item}</Link>)}<Link to="/events?category=other">Activities</Link></nav><nav className="sub-nav"><Link to="/events">List your show</Link><Link to="/events"><Tag size={13} /> Offers</Link></nav></div></div>
    {searchOpen && <SearchOverlay close={() => setSearchOpen(false)} />}
  </header>;
}

function SearchOverlay({ close }) {
  const navigate = useNavigate();
  const [value, setValue] = useState('');
  return <div className="search-overlay"><div className="search-overlay-inner"><button className="icon-button" onClick={close}><ChevronLeft size={20} /></button><input autoFocus placeholder="Search movies, concerts, sports & events" value={value} onChange={e => setValue(e.target.value)} onKeyDown={e => e.key === 'Enter' && navigate(`/events?query=${value}`)} /><button className="search-submit" onClick={() => navigate(`/events?query=${value}`)}><Search size={17} /> Search</button></div></div>;
}

function Home({ location }) {
  const navigate = useNavigate();
  const localEvents = events.filter(e => e.city === location || location === 'Hyderabad');
  return <main>
    <section className="promo-band"><div className="container"><div className="promo-hero"><img src="/assets/universal-hero.png" alt="Live entertainment" /><div className="promo-copy"><span>LIVE THIS WEEKEND</span><h1>Big moments.<br />One place.</h1><p>Tickets for every version of a good night.</p><button onClick={() => navigate('/events')}>Explore now <ArrowRight size={16} /></button></div><div className="promo-dots"><i className="active" /><i /><i /><i /></div></div></div></section>
    <section className="section rec-section" id="trending"><div className="container"><SectionHeading title="Recommended movies" action="See all" href="/movies" /><div className="interest-row"><button className="active">Hindi</button><button>Telugu</button><button>English</button><button>Tamil</button><button>Malayalam</button><button>Kannada</button></div><div className="event-grid featured-grid">{localEvents.slice(0, 5).map(e => <EventCard event={e} key={e.id} />)}</div></div></section>
    <section className="explore-strip"><div className="container"><Link to="/events?category=movies"><Film /><span>Movies</span><small>Now showing</small></Link><Link to="/events?category=concerts"><Music2 /><span>Concerts</span><small>Live music</small></Link><Link to="/events?category=sports"><Trophy /><span>Sports</span><small>Feel the game</small></Link><Link to="/events?category=theatre"><Drama /><span>Plays</span><small>Stage stories</small></Link><Link to="/events?category=comedy"><Laugh /><span>Comedy</span><small>Laugh out loud</small></Link><Link to="/events"><Popcorn /><span>Experiences</span><small>Something new</small></Link></div></section>
    <section className="section section-muted"><div className="container"><SectionHeading title="The best of live events" action="See all" href="/events?category=concerts" /><div className="event-grid featured-grid">{[events[0], events[2], events[3], events[4], events[5]].map(e => <EventCard event={e} key={e.id} />)}</div></div></section>
    <section className="container offer-banner"><div><span>UNIVERSAL PREMIERE</span><h2>Experiences made<br />for your weekend.</h2><p>Find early access, member-only events, and the best seats in the house.</p><button onClick={() => navigate('/events')}>Explore premieres <ArrowRight size={16} /></button></div><img src="https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?auto=format&fit=crop&w=1200&q=85" alt="Festival stage" /></section>
    <section className="section browse-section"><div className="container"><SectionHeading title="Browse events by category" /><div className="category-grid">{categories.map(c => <Link className={`category-card ${c.tone}`} to={`/events?category=${c.label.toLowerCase()}`} key={c.label}><span className="category-icon">{c.icon}</span><div><h3>{c.label}</h3><p>{c.count}</p></div><ArrowRight size={18} /></Link>)}</div></div></section>
    <Footer />
  </main>;
}

function SectionHeading({ eyebrow, title, action, href }) { return <div className="section-heading"><div><div className="eyebrow ink">{eyebrow}</div><h2>{title}</h2></div>{action && <Link className="text-link" to={href}>{action} <ArrowRight size={16} /></Link>}</div>; }
function Promise({ icon, title, copy }) { return <div className="promise"><span>{icon}</span><div><h3>{title}</h3><p>{copy}</p></div></div>; }
function EventCard({ event }) { return <Link className="event-card" to={`/events/${event.id}`}><div className={`event-image ${event.accent}`}><img src={event.image} alt={event.title} /><span className="event-type">{event.type}</span><button className="heart" aria-label="Save event" onClick={e => e.preventDefault()}><Heart size={17} /></button></div><div className="event-card-body"><div className="event-card-title"><h3>{event.title}</h3><ArrowRight size={17} /></div><p className="event-venue">{event.venue} · {event.city}</p><div className="event-card-meta"><span><CalendarDays size={14} /> {event.date}</span><strong>From ₹{event.price.toLocaleString('en-IN')}</strong></div></div></Link>; }

function EventsPage({ location }) { const [searchParams] = useSearchParams(); const pathCategory = useLocation().pathname.slice(1); const query = (searchParams.get('query') || '').toLowerCase(); const category = searchParams.get('category') || (['movies', 'concerts', 'sports', 'theatre', 'comedy'].includes(pathCategory) ? pathCategory : ''); const filtered = events.filter(e => (!category || e.type.toLowerCase() === category || (category === 'other' && !['movies','concerts','sports','theatre','comedy'].includes(e.type.toLowerCase()))) && (!query || `${e.title} ${e.venue} ${e.city}`.toLowerCase().includes(query))); return <main className="listing-page"><div className="container listing-head"><div><div className="eyebrow ink">EXPLORE THE LINEUP</div><h1>{category ? `${category[0].toUpperCase()}${category.slice(1)} events` : query ? `Results for “${query}”` : 'All experiences'}</h1><p>{filtered.length} experiences near {location}</p></div><button className="filter-button"><Compass size={16} /> Filters <ChevronDown size={15} /></button></div><div className="container event-grid listing-grid">{filtered.length ? filtered.map(e => <EventCard event={e} key={e.id} />) : <div className="empty-state"><Compass size={26} /><h3>No events found in {location}.</h3><p>Try a different category or search term.</p></div>}</div><Footer /></main>; }

function EventDetails() { const { id } = useParams(); const event = events.find(e => e.id === id) || events[0]; const navigate = useNavigate(); const [qty, setQty] = useState(2); const [ticket, setTicket] = useState('Premium'); return <main className="details-page"><div className="container"><Link className="back-link" to="/events"><ChevronLeft size={16} /> All events</Link><div className="detail-layout"><div className="detail-visual"><img src={event.image} alt={event.title} /><div className="detail-caption"><span>{event.type}</span><span>EVT-2026-000001</span></div></div><div className="detail-info"><div className="eyebrow ink">{event.type.toUpperCase()} <span className="verified"><Check size={12} /> VERIFIED ORGANIZER</span></div><h1>{event.title}</h1><p className="detail-description">{event.description}</p><div className="detail-facts"><div><CalendarDays size={18} /><span><b>{event.date}</b><small>Saturday</small></span></div><div><Clock3 size={18} /><span><b>{event.time}</b><small>Doors open 1 hr before</small></span></div><div><MapPin size={18} /><span><b>{event.venue}</b><small>{event.city}</small></span></div></div><div className="ticket-panel"><div className="ticket-panel-head"><span>Choose your ticket</span><small>Prices include all taxes</small></div>{['General', 'Regular', 'Premium', 'VIP'].map((name, i) => <button className={`ticket-option ${ticket === name ? 'selected' : ''}`} key={name} onClick={() => setTicket(name)}><span><b>{name}</b><small>{['Standard entry', 'Great view', 'Best available', 'Front row access'][i]}</small></span><strong>₹{[499, 799, 1299, 2499][i].toLocaleString('en-IN')}</strong></button>)}<div className="ticket-bottom"><div><small>Quantity</small><div className="quantity"><button onClick={() => setQty(Math.max(1, qty - 1))}>−</button><strong>{qty}</strong><button onClick={() => setQty(qty + 1)}>+</button></div></div><div className="total"><small>Total</small><strong>₹{(qty * { General: 499, Regular: 799, Premium: 1299, VIP: 2499 }[ticket]).toLocaleString('en-IN')}</strong></div></div><button className="button button-primary full" onClick={() => navigate(`/booking/${event.id}`)}>Book now <ArrowRight size={17} /></button></div></div></div></div><Footer /></main>; }

function BookingPage() { const { id } = useParams(); const event = events.find(e => e.id === id) || events[0]; const navigate = useNavigate(); const [paid, setPaid] = useState(false); if (paid) return <Confirmation event={event} />; return <main className="booking-page"><div className="container narrow"><div className="stepper"><span className="active">01 <b>Event</b></span><i /><span className="active">02 <b>Tickets</b></span><i /><span>03 <b>Payment</b></span><i /><span>04 <b>Done</b></span></div><div className="booking-layout"><div><Link className="back-link" to={`/events/${event.id}`}><ChevronLeft size={16} /> Back to event</Link><div className="booking-header"><div className="eyebrow ink">YOUR TICKETS</div><h1>Almost there.</h1><p>Review your selection and complete your booking securely.</p></div><div className="payment-card"><div className="booking-event"><img src={event.image} alt={event.title} /><div><span>{event.type}</span><h3>{event.title}</h3><p>{event.date} · {event.time}<br />{event.venue}, {event.city}</p></div></div><div className="payment-section"><label>Payment method</label><div className="payment-tabs"><button className="active">UPI</button><button>Card</button><button>Net Banking</button><button>Wallet</button></div><label>UPI ID</label><input placeholder="name@bank" /><p className="secure-note"><ShieldCheck size={14} /> Your payment is secured with bank-grade encryption.</p></div></div></div><aside className="summary"><h3>Booking summary</h3><div className="summary-row"><span>Premium × 2</span><strong>₹2,598</strong></div><div className="summary-row"><span>Convenience fee</span><strong>₹52</strong></div><div className="summary-row"><span>GST</span><strong>₹477</strong></div><div className="summary-total"><span>Total payable</span><strong>₹3,127</strong></div><button className="button button-primary full" onClick={() => setPaid(true)}>Pay ₹3,127 <ArrowRight size={17} /></button></aside></div></div></main>; }
function Confirmation({ event }) { return <main className="confirmation-page"><div className="confirmation-card"><div className="success-mark"><Check size={30} /></div><div className="eyebrow ink">BOOKING CONFIRMED</div><h1>You’re all set.</h1><p className="confirmation-intro">Your tickets are ready. We’ve sent the details to rahul.sharma@gmail.com.</p><div className="ticket-receipt"><div><span>Booking ID</span><strong>BOOK-2026-000001</strong></div><div><span>Event</span><strong>{event.title}</strong></div><div><span>When</span><strong>{event.date} · {event.time}</strong></div><div><span>Tickets</span><strong>2 Premium tickets</strong></div><div><span>Total paid</span><strong>₹3,127</strong></div></div><div className="confirmation-actions"><Link className="button button-primary" to="/my-bookings">View booking <ArrowRight size={17} /></Link><button className="button button-secondary">Download ticket</button></div><Link className="text-link centered" to="/">Back to home</Link></div></main>; }

function LoginPage({ setUser }) { const navigate = useNavigate(); const [role, setRole] = useState('customer'); return <main className="auth-page"><div className="auth-art"><div className="auth-art-copy"><span>Universal Tickets</span><h1>Good nights<br />start here.</h1><p>One place for the shows, matches, and stories you are looking forward to.</p></div></div><div className="auth-panel"><Link className="brand auth-brand" to="/"><span className="brand-mark"><Ticket size={18} /></span><span>UNIVERSAL <em>TICKETS</em></span></Link><div className="auth-content"><div className="eyebrow ink">WELCOME BACK</div><h1>Log in to continue.</h1><p>Pick up where you left off.</p><div className="role-tabs"><button className={role === 'customer' ? 'active' : ''} onClick={() => setRole('customer')}>Customer</button><button className={role === 'organizer' ? 'active' : ''} onClick={() => setRole('organizer')}>Organizer</button><button className={role === 'verifier' ? 'active' : ''} onClick={() => setRole('verifier')}>Verifier</button></div><label>Email address</label><input placeholder="you@example.com" /><label>Password</label><input type="password" placeholder="Enter your password" /><div className="auth-options"><label className="checkbox"><input type="checkbox" /> Remember me</label><button>Forgot password?</button></div><button className="button button-primary full" onClick={() => { setUser({ role }); navigate(role === 'organizer' ? '/organizer' : role === 'verifier' ? '/verifier' : '/'); }}>Log in <ArrowRight size={17} /></button><p className="auth-switch">New to Universal Tickets? <Link to="/register">Create an account</Link></p></div></div></main>; }
function RegisterPage() { return <main className="auth-page simple-auth"><div className="auth-panel centered-panel"><Link className="brand auth-brand" to="/"><span className="brand-mark"><Ticket size={18} /></span><span>UNIVERSAL <em>TICKETS</em></span></Link><div className="auth-content"><div className="eyebrow ink">JOIN THE EXPERIENCE</div><h1>Create your account.</h1><p>Save events, manage bookings, and never miss the good stuff.</p><label>Full name</label><input placeholder="Rahul Sharma" /><label>Email address</label><input placeholder="you@example.com" /><label>Password</label><input type="password" placeholder="Create a password" /><button className="button button-primary full">Create account <ArrowRight size={17} /></button><p className="auth-switch">Already have an account? <Link to="/login">Log in</Link></p></div></div></main>; }
function BookingsPage() { return <main className="listing-page"><div className="container listing-head"><div><div className="eyebrow ink">YOUR UNIVERSE</div><h1>My bookings</h1><p>Keep every plan in one place.</p></div></div><div className="container booking-tabs"><button className="active">Upcoming <span>2</span></button><button>Completed</button><button>Cancelled</button></div><div className="container my-bookings-list">{events.slice(0, 2).map((event, i) => <div className="booking-card" key={event.id}><img src={event.image} alt={event.title} /><div className="booking-card-main"><div className="booking-card-top"><span className="status upcoming">UPCOMING</span><span>BOOK-2026-00000{i + 1}</span></div><h3>{event.title}</h3><p>{event.date} · {event.time} · {event.venue}</p><div className="booking-card-bottom"><strong>2 Premium tickets</strong><strong>₹{(event.price * 2).toLocaleString('en-IN')}</strong></div></div><Link className="icon-button" to={`/events/${event.id}`}><ArrowRight size={18} /></Link></div>)}</div><Footer /></main>; }
function RoleDashboard({ role }) { return <main className="dashboard-page"><div className="container dashboard-head"><div><div className="eyebrow ink">{role.toUpperCase()} WORKSPACE</div><h1>Good morning, {role === 'Organizer' ? 'Skyline Events' : 'Suresh'}.</h1><p>{role === 'Organizer' ? 'Your live experiences, all in one view.' : 'Keep the Universal Tickets community moving.'}</p></div><div className="dashboard-date"><CalendarDays size={16} /> 09 September 2026</div></div><div className="container stats-grid"><div><span>Total {role === 'Organizer' ? 'events' : 'applications'}</span><strong>{role === 'Organizer' ? '24' : '18'}</strong><small>+12% this month</small></div><div><span>{role === 'Organizer' ? 'Bookings' : 'Pending review'}</span><strong>{role === 'Organizer' ? '1,284' : '07'}</strong><small>Needs your attention</small></div><div><span>{role === 'Organizer' ? 'Venues' : 'Approved this month'}</span><strong>{role === 'Organizer' ? '06' : '32'}</strong><small>Across all cities</small></div></div><div className="container dashboard-content"><div className="dashboard-table"><div className="table-head"><h2>{role === 'Organizer' ? 'Upcoming events' : 'Applications to review'}</h2><button className="text-link">View all <ArrowRight size={15} /></button></div>{(role === 'Organizer' ? events.slice(0, 4) : ['Skyline Events Pvt Ltd', 'LiveWave Concerts', 'PrimeStage Entertainment', 'Royal Sports Events']).map((item, i) => <div className="table-row" key={item.id || item}><div className="table-avatar">{role === 'Organizer' ? <img src={item.image} alt="" /> : <UserRound size={16} />}</div><div><strong>{item.title || item}</strong><span>{role === 'Organizer' ? `${item.date} · ${item.venue}` : `ORG-2026-00000${i + 2} · Hyderabad`}</span></div><span className={`status ${role === 'Organizer' ? 'upcoming' : 'review'}`}>{role === 'Organizer' ? 'PUBLISHED' : 'PENDING'}</span><ArrowRight size={16} /></div>)}</div><div className="side-note"><div className="eyebrow ink">QUICK ACTIONS</div><h3>{role === 'Organizer' ? 'Keep your calendar full.' : 'Small reviews, big nights.'}</h3><p>{role === 'Organizer' ? 'Your next great event could be one conversation away.' : 'Review organizer applications and help fans find their next experience.'}</p><button className="button button-secondary">{role === 'Organizer' ? 'Create event' : 'Review queue'} <ArrowRight size={16} /></button></div></div></main>; }

function Footer() { return <footer className="site-footer"><div className="container footer-top"><div><Link className="brand footer-brand" to="/"><span className="brand-mark"><Ticket size={18} /></span><span>UNIVERSAL <em>TICKETS</em></span></Link><p>Discover. Book. Experience.<br />The moments worth showing up for.</p></div><div className="footer-links"><div><span>Explore</span><Link to="/events">All events</Link><Link to="/events?category=movies">Movies</Link><Link to="/events?category=concerts">Concerts</Link></div><div><span>Universal</span><Link to="/register">List your event</Link><Link to="/login">Organizer login</Link><a href="mailto:hello@universaltickets.in">Contact us</a></div><div><span>Follow along</span><a href="#">Instagram</a><a href="#">Threads</a><a href="#">LinkedIn</a></div></div></div><div className="container footer-bottom"><span>© 2026 Universal Tickets</span><span>Made for the moments that matter.</span><span>Privacy · Terms</span></div></footer>; }

createRoot(document.getElementById('root')).render(<BrowserRouter><App /></BrowserRouter>);
